---
title: "Phoca vitulina"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r my_setup, echo=FALSE}
source("/home/oamace28/ColbyForecasting/setup.R")
```
[Harbor seals](https://en.wikipedia.org/wiki/Harbor_seal) (Phoca vitulina) 
```{r data, echo=FALSE}
cfg = read_configuration(scientificname = "Phoca vitulina", version = "v1")
model_input = read_model_input(scientificname = "Phoca vitulina", 
                               version = "v1",
                               log_me = c("depth", "Xbtm")) |>
  dplyr::mutate(month = month_as_number(.data$month)) |>
  select(all_of(c("class", cfg$keep)))
```

```{r model, echo=FALSE}
model_input_split = spatial_initial_split(model_input, 
                        prop = 1 / 5,     # 20% for testing
                        strategy = spatial_block_cv) # see ?spatial_block_cv
```

```{r split_plot, echo=FALSE}
autoplot(model_input_split)
```

```{r plot_data, echo=FALSE}
tr_data = training(model_input_split)
cv_tr_data <- spatial_block_cv(tr_data,
  v = 5,     
  cellsize = grid_cellsize(model_input),
  offset = grid_offset(model_input) + 0.00001
)
autoplot(cv_tr_data)
```

```{r recipe_+_summary, echo=FALSE}
one_row_of_training_data = dplyr::slice(tr_data,1)
rec = recipe(one_row_of_training_data, formula = class ~ .)
rec
summary(rec)
```

```{r workflow, echo=FALSE}
wflow = workflow_set(
  
  preproc = list(default = rec), # not much happening in our preprocessor
  
  models = list(                 # but we have 4 models to add
    
      # very simple - nothing to tune
      glm = logistic_reg(
          mode = "classification") |>
        set_engine("glm"),
      
      # two knobs to tune
      rf = rand_forest(
          mtry = tune(),
          trees = tune(),
          mode = "classification") |>
        set_engine("ranger", 
                   importance = "impurity"),
      
      # so many things to tune!
      btree = boost_tree(
          mtry = tune(), 
          trees = tune(), 
          tree_depth = tune(), 
          learn_rate = tune(), 
          loss_reduction = tune(), 
          stop_iter = tune(),
          mode = "classification") |>
        set_engine("xgboost"),
    
      # just two again
      maxent = maxent(
          feature_classes = tune(),
          regularization_multiplier = tune(),
          mode = "classification") |>
        set_engine("maxnet")
  )
)
wflow
```

```{r Metrics_+_fit , echo=FALSE}
metrics = sdm_metric_set(yardstick::accuracy)

wflow <- wflow |>
  workflow_map("tune_grid",
    resamples = cv_tr_data, 
    grid = 3,
    metrics = metrics, 
    verbose = TRUE)
```

```{r wflow_plot, echo=FALSE}
autoplot(wflow)
```

```{r best_model, echo=FALSE}
model_fits = workflowset_selectomatic(wflow, model_input_split,
                                  filename = "Phoca_vitulina-v1-model_fits",
                                  path = data_path("models"))

model_fit_metrics(model_fits)

model_fit_confmat(model_fits)
```

```{r model_fit, echo=FALSE}
model_fit_roc_auc(model_fits)
```

```{r plot_model, echo=FALSE}
model_fit_varimp_plot(model_fits)
```

```{r rf_plot, echo=FALSE}
rf = model_fits |>
  filter(wflow_id == "default_rf")

autoplot(rf$splits[[1]])
```

```{r btree_plot, echo=FALSE}
rf$.metrics[[1]]

rf$.predictions[[1]]

rf$.workflow[[1]]

model_fit_pdp(model_fits, wid = "default_btree", title = "Boosted Tree")
```

